library(googleVis)
library(quantmod)
library(shiny)
library(ggplot2)
library(dplyr)
library(forecast)
library(TTR)
library(data.table)
library(zoo)
library(shinydashboard)
library(DT)
library(textshape)
library(plotly)
library(tidyr)
library(rsconnect)
library(dygraphs)
library(tm)
library(SnowballC)
library(wordcloud)
library(rvest)
library(tseries)
library(shinyWidgets)
library(gridExtra)
library(tm.plugin.webmining)
library(openNLP)
library("qdap")
library(RCurl)
library(twitteR)
library(grid)
library(lubridate)
library(newsapi)

source('TwitterAuth.R')
source('input.R')
source('WebMining.R')

# Creating full names for the stocks with company name
for ( i in 1:dim(stockInfo)[1] ) {
    stockInfo[i, "FullName"] = paste( stockInfo[i, "Stock.SYM"], " (", stockInfo[i, "Name"], ")", sep = "") 
}

